baseURL = "/"
languageCode = "zh-cn"
title = "🍀 Clover Blog"
theme = "PaperMod"
publishDir = "public"
paginate = 5
summaryLength = 30

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
