baseURL = "/"
languageCode = "zh-cn"
title = "Clover Blog"
theme = "PaperMod"
paginate = 5
summaryLength = 30

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false

[params]
  label = { text = "Clover Blog", icon = "/clover-logo.svg" }

[menu]
  [[menu.main]]
    name = "工具"
    URL = "https://tools.xsanye.cn"
    weight = 1
  [[menu.main]]
    name = "关于"
    URL = "/about"
    weight = 2
